

app = "solana-bankingstage-geyser-sidecar-migrate-hetzner"
primary_region = "fra"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  RUST_LOG = "info,grpc_banking_transactions_notifications=debug"

[metrics]
  path = "/"
  port = 9091
