name: Cargo Check & Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_check:
    name: cargo check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # The toolchain action should definitely be run before the cache action
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true

      - name: Rust Check
        run: |
          cargo check --locked --workspace --all-targets
          
      - name: Run Tests
        run: RUST_LOG=info cargo test
